registro/urls.py
from django.contrib import admin
from django.urls import path,include
from registro import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    # path('login',views.login_page,name='login-page'),
    # path('user_login',views.login_user,name='login-user'),
    path('logout',views.logout_user,name='logout'),
    path('employee_list',views.employee_list,name='employee-page'), 
    path('add_employee',views.manage_employee,name='add-employee'),
    path('edit_employee/<int:pk>',views.manage_employee,name='edit-employee'),
    path('save_employee',views.save_employee,name='save-employee'),
    path('view_card/<int:pk>',views.view_card,name='view-card'),
    path('view_details/<str:code>',views.view_details,name='view-details'),
    path('view_details',views.view_details,name='scanned-code'),
    path('scanner',views.view_scanner,name='view-scanner'),
    path('end_visit/<int:code>', views.end_visit, name='end-visit'),
    path('delete_employee/<int:pk>',views.delete_employee,name='delete-employee'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simpleproject/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import re_path
from django.conf.urls import include
from people.views import PersonListView, PersonCreateView, PersonUpdateView, ReportePersonasPDF, PersonCheckView, searchPerson, saveCheckedPerson, PersonBajaListView, GetPersonas, InsertBaja, DirectoryListView, GetPersonasDirectory, GetCompPersonas, InsertComp, PersonCompListView, DetalleIncidencias, PersonInciListView, ReporteIncidenciasPDF, UpdateIncidencia, GetPersonasIncidencia, AddIncidencia, DeleteIncidencia, PersonDirectoryUpdateView, DeleteComp, AreasListView, json_to_pdf, GetPersonasCompensacion, compensacionesArea, IncidenciaConsulta, ValidatePersonIncidencia, DetailPersonIncidencia, GetIncidenciaTable, \
    loginAdmin, AdminConsulta, AdminInciListView, GetAdminIncidencia, reporteIncidencias, PersonAyudaListView, GetAyudaPersonas, InsertAyuda, DeleteAyuda, GetPersonasAyuda, DashboardCheck, UpdateDashboard, \
        GetPersonaAyuda,  SersocListView, SersocCreateView, CreateSersocPerson, AddAyuda, DeleteAyudaMonto, ValidateRFC, PersonVacacionesListView, GetPersonasVacacion, GetDetalleVacacion, \
        GetAsistencia, DeleteDayVacacion, SersocAsistListView, \
        CapacitacionCreateView, CapacitacionListView, SaveCapacitacion, loginUsers, CapacitacionView, CapacitacionesxPersona, SaveCapacitacionEvidencia, CapacitacionXCursoView, UpdateStatusEvidencia
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from crede_api import urls as crede_urls

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    
    path('', PersonListView.as_view(), name='person_list'),
    path('activos/personas',PersonListView.as_view(), name='activos_list'),
    path('bajas/personas', PersonBajaListView.as_view(), name='baja_list' ),
    path('get_personas/', GetPersonas, name="get_Personas"),
    path('insert_baja/', InsertBaja, name="insert_baja"),

    #Vacaciones
    path('vacaciones/personas', PersonVacacionesListView.as_view(), name='vacaciones_list' ),
    path('vacaciones/busqueda', GetPersonasVacacion , name='search_person_vacacion'),
    path('vacaciones/detalle', GetDetalleVacacion , name='detail_vacacion'),
    path('vacaciones/delete', DeleteDayVacacion, name='delete_vacacion'),

    #Compensaciones
    path('compensaciones/personas', PersonCompListView.as_view(), name='comp_list' ),
    path('get_personas_comp/', GetCompPersonas, name="get_PersonasComp"),
    path('compensaciones/insert/', InsertComp, name="insert_comp"),
    path('compensaciones/delete', DeleteComp, name='delete_Compensacion' ),
    path('compensaciones/print/<str:fechaInicio>/<str:fechaFin>/<int:folio>', json_to_pdf, name='print_Compensaciones'),
    path('compensaciones/printarea/<str:fechaInicio>/<str:fechaFin>/<int:folio>', compensacionesArea, name='print_CompensacionesArea'),
    path('search_compensacion/', GetPersonasCompensacion, name='search_person_compensacion'),

    #Incidencias
    path('incidencias/personas', PersonInciListView.as_view(), name='inci_list' ),
    path('incidencias/imprimir/<int:pk>/<str:fechaInicio>/<str:fechaFin>', ReporteIncidenciasPDF.as_view(), name="incidencia_print_rango"),
    path('incidencias/detalle/<int:pk>/<str:fechaInicio>/<str:fechaFin>',  login_required(DetalleIncidencias.as_view()), name="detalle_incidencia_rango"),
    path('incidencias/detalle/<int:pk>/<str:fechaInicio>/',  login_required(DetalleIncidencias.as_view()), name="detalle_incidencia"),
    
    path('incidencias/update', UpdateIncidencia, name='update_Incidencia' ),
    path('incidencias/add', AddIncidencia, name='add_Incidencia' ),
    path('incidencias/delete', DeleteIncidencia, name='delete_Incidencia' ),
    path('search_incidencia/', GetPersonasIncidencia, name='search_person_incidencia'),
    path('incidencias/imprimir/<int:pk>/<str:fechaInicio>/<str:fechaFin>/<str:bases>', ReporteIncidenciasPDF.as_view(), name="print_all_Incidencia" ),
    

    #Consulta Incidencias por Personal
    path('incidencia/login', IncidenciaConsulta.as_view(), name="incidencia_consulta"),
    path('incidencia/validate', ValidatePersonIncidencia, name="validate_person"),
    path('incidencia/detail/<str:pk>', DetailPersonIncidencia.as_view()),
    path('incidencia/get/table', GetIncidenciaTable, name="get_incidencias"),
    #Consulta de Incidencias por Directivos
    path('incidencia/admin/login', AdminConsulta.as_view()),
    path('incidencia/admin/validate', loginAdmin, name="consulta_admin"),
    path('incidencia/admin/personas/<str:matricula>', AdminInciListView.as_view(), name='inci_list' ),
    path('incidencia/admin/search', GetAdminIncidencia, name='search_admin_incidencia'),
    path('incidencias/detalle/<str:admin>/<int:pk>/<str:fechaInicio>/<str:fechaFin>', DetalleIncidencias.as_view(), name="admin_detalle_incidencia_rango"),
    path('incidencias/reporte/<int:incidencia>/<str:fechaInicio>/<str:fechaFin>', reporteIncidencias, name="reporte_incidencia"),
    path('incidencia/admin/dashboard',DashboardCheck.as_view(), name="dashboard_admin"),
    path('incidencia/admin/update_dashboard', UpdateDashboard , name='update_dashboard'),
   

    path('admin/', admin.site.urls),
    path('add/', PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/edit/', PersonUpdateView.as_view(), name='person_edit'),
    path('<int:pk>/print/', ReportePersonasPDF.as_view(), name='person_print'),
    
    #Checador
    path('check/', PersonCheckView.as_view(), name='person_check'),
    path('checked/', saveCheckedPerson, name='person_check'),
    path('searchecked/', searchPerson, name='person_search'), 
    ###########
    
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('filter/<str:q>/', PersonCreateView.as_view(), name='person_filter'),
    #path('incidencia/<str:person>/changeIncidencias/<str:year>/<str:month>/<str:day><str:photo>', showImage, name='show_Imagen'),
    
    #Directorio
    path('directorio/personas',DirectoryListView.as_view(), name='directorio'),
    path('directorio/search', GetPersonasDirectory, name='search_directory'),
    path('<int:pk>/directory/edit/', PersonDirectoryUpdateView.as_view(), name='person_directory_edit'),    

    #Areas
    path('areas', AreasListView.as_view(), name='areas_list' ),

    ##Ayudas
    path('ayuda/personas', PersonAyudaListView.as_view(), name='ayuda_list' ),
    path('get_personas_ayuda/', GetAyudaPersonas, name="get_PersonasAyuda"),
    path('ayuda/agregar/', AddAyuda, name='add_ayuda'),
    path('ayuda/insert/', InsertAyuda, name="insert_ayuda"),
    path('ayuda/delete', DeleteAyuda, name='delete_ayuda' ),
    path('ayuda/monto/delete', DeleteAyudaMonto, name='delete_ayuda_monto'),
    path('search_ayuda/', GetPersonasAyuda, name='search_person_ayuda'),
    path('search/ayuda/area', GetPersonaAyuda, name="get_PersonaAyuda"),

    #Servicio Social
    #path('add/sersoc/', SersocCreateView.as_view(), name='sersoc_add'),
    path('add/sersoc/', CreateSersocPerson, name='sersoc_add'),
    path('<int:pk>/edit/sersoc/', CreateSersocPerson, name='sersoc_edit'),
    path('<int:pk>/<int:sersoc>/print/sersoc/', ReportePersonasPDF.as_view(), name='sersoc_print'),
    path('<int:person>/asist/sersoc/', SersocAsistListView.as_view(), name='sersoc_asist'),
    path('sersoc/', SersocListView.as_view(), name='sersoc_list'),

    #Consulta 
    path('consulta/<str:rfc>/', ValidateRFC, name='validate_rfc'),

    #Capacitacion
    
    path('capacitacion/', CapacitacionListView.as_view(), name='capacitacion_list'),
    path('capacitacion/add/', SaveCapacitacion, name='save_capacitacion'),
    path('<int:pk>/edit/', PersonUpdateView.as_view(), name='capacitacion_edit'),
    path('capacitacion/login', loginUsers, name="capacitacion_login"), 
    path('capacitacion/users', CapacitacionView.as_view(), name="capacitacion_users"), 
    path('capacitacion/persona/<str:matricula>', CapacitacionesxPersona.as_view(), name="capacitacion_persona"),
    path('capacitacion/persona/save/', SaveCapacitacionEvidencia, name="save_capacitacion_persona"),
    path('capacitacion/curso/<int:pk>/', CapacitacionXCursoView.as_view(), name="capacitacion_curso"),
    path('capacitacion/update/', UpdateStatusEvidencia, name="update_status_capacitacion"),
    
    #Api URL's
    path('api-auth/', include('rest_framework.urls')),
    path('', include(crede_urls)),
]   

people/backup/forms.py
from django import forms
from django.core.validators import RegexValidator
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from people.models import Incidencia, Person
from django.forms.widgets import NumberInput
from multi_email_field.forms import MultiEmailField
import datetime
class PersonForm(forms.ModelForm):
    rfc = forms.CharField(max_length=13, label="RFC CON HOMOCLAVE", required=False, validators=[
        RegexValidator('^([A-Z,Ñ,&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[A-Z|\d]{3})$',
                       message="Introduzca un RFC válido")])
    curp = forms.CharField(max_length=20, label="CURP ", required=False, validators=[RegexValidator(
        '^[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}$',
        message="Introduzca un CURP válido")])
    telefono1 =  forms.CharField(max_length=15, required=False, label="Teléfono 1",
                               validators=[RegexValidator('^\d{4,}$', message="Introduzca un Teléfono válido")])
    telefono2 =  forms.CharField(max_length=15, required=False, label="Teléfono 2",
                               validators=[RegexValidator('^\d{4,}$', message="Introduzca un Teléfono válido")])
    emergencia_telefono =  forms.CharField(max_length=15, required=False, label="Teléfono Emergencia",
                               validators=[RegexValidator('^\d{4,}$', message="Introduzca un Teléfono válido")])
    email_personal = forms.EmailField(required=True)
    email_institucional = MultiEmailField()

    fecha_ingreso = forms.DateField(input_formats=['%d/%m/%Y'])

    imagen_base64 = forms.HiddenInput()
    class Meta:
        model = Person
        fields = '__all__'
        


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))
        #self.fields['fecha_ingreso'].widget.attrs['class'] = 'datepicker'
        self.fields['curp'].widget.attrs['onkeyup'] = 'javascript:this.value=this.value.toUpperCase();'
        self.fields['rfc'].widget.attrs[' onkeyup'] = 'javascript:this.value=this.value.toUpperCase();'
       
class IncidenciaForm(forms.ModelForm):
    class Meta:
        model = Incidencia
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save Incidencia'))
       

people/views/areasView.py

from django.shortcuts import render
from django.urls import reverse_lazy
from people.models import AreaOrganigrama, Compensacion, Compensaciones, Person, Incidencia, Bajas, AreaInterna, CausaIncidencia
from people.forms import AreaForm
from django.views.generic import ListView, CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

@method_decorator(login_required, name='dispatch')
class AreasListView(ListView):
    model = AreaOrganigrama
    def get(self, request, *args, **kwargs):
        queryset =AreaOrganigrama.objects.all()
        querysetAI = AreaInterna.objects.all()

        content = {#t.render(
            'areaOrganigrama': queryset, 
            'areaInterna' : querysetAI,
        }#)
        return render(request, 'people/area/area_list.html' , content)    

class AreasUpdateView(UpdateView):
    model = AreaOrganigrama
    form_class = AreaForm
    template_name = 'people/areas/areas_form_update.html'
    success_url =  reverse_lazy('activos_list')


class AreasCreateView(CreateView):
    model = AreaOrganigrama
    form_class = AreaForm
    template_name = 'people/areas/areas_form.html'
    success_url = reverse_lazy('person_list')
   

people/views/consulta.py
from people.models import  Person
from django.http.response import JsonResponse
from django.db.models import Q
def ValidateRFC(request, rfc):
    status = 200
    if request.method == 'GET':
        try:
            person = Person.objects.get(Q(rfc__unaccent__icontains=rfc) & Q(activo=True))
            person_data={"nombre": person.nombres, "apellido1": person.apellido1, "apellido2": person.apellido2,"matricula":person.matricula, "curp":person.curp } 
        except Person.DoesNotExist:
          status = 400 
          person_data={"error":"RFC no encontrado"}
    return JsonResponse(person_data,status=status)    

people/views/convertExcel.py
import xlwt
from django.http import HttpResponse
from django.contrib.auth.models import User

def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="users.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Users Data') # this will make a sheet named Users Data

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Username', 'First Name', 'Last Name', 'Email Address', ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style) # at 0 row 0 column 

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = User.objects.all().values_list('username', 'first_name', 'last_name', 'email')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)

    return response

templates/people/capacitacion/capacitacion_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


 
{% block content %}

{{ form.media.js }}
{{ form.media.js }}
  <form method="post" novalidate>
    {% csrf_token %}
    
    <div class="row">
      <div class="col-md-4">
        {{ form.nombres|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.apellido1|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.apellido2|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.curp|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.rfc|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.cat_contratacion|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.areaInterna|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.cat_area_org|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.puesto|as_crispy_field }}
      </div>
     
      <div class="col-md-4">
        {{ form.fecha_ingreso|as_crispy_field }}
      </div>
      <div class="col-md-4">
        {{ form.cat_nombramiento|as_crispy_field }}
      </div>
      
     
    </div>
    <div class="row">
      <div class="col-md-4  alert alert-info">
          {{ form.cat_horario|as_crispy_field }}
      </div>
       <div class="col-md-4 alert alert-info">
          {{ form.horario_finde|as_crispy_field }}
      </div>
     
     
    </div>
    <div class="row">
      <div class="alert alert-info col-md-8">
          {{ form.email_institucional|as_crispy_field }}
      </div>
      <div class="alert alert-info col-md-4">
        {{ form.extension_telefonica|as_crispy_field }}
    </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        {{ form.cat_entidades_federativas|as_crispy_field }}
      </div>
      <div class="col-md-3">
        {{ form.municipio|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.cp|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.colonia|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.nombre_via|as_crispy_field }}
      </div>
      <div class="col-md-3">
        {{ form.num_exterior|as_crispy_field }}
      </div>
      <div class="col-md-3">
        {{ form.num_interior|as_crispy_field }}
      </div>
     
      <div class="col-md-3">
        {{ form.cat_tipo_via|as_crispy_field }}
      </div>
    </div>
    <div class="row">  
      <div class="col-md-4">
        {{ form.email_personal|as_crispy_field }}
      </div> 
      <div class="col-md-4">
        {{ form.telefono1|as_crispy_field }}
      </div> 
      <div class="col-md-4">
        {{ form.telefono2|as_crispy_field }}
      </div> 
    </div>
    <div class="row">  
      <div class="col-md-6">
        {{ form.emergencia_contacto|as_crispy_field }}
      </div>
      <div class="col-md-6">
        {{ form.emergencia_cat_relacion|as_crispy_field }}
      </div>
       
      <div class="col-md-6">
        {{ form.emergencia_telefono|as_crispy_field }}
      </div> 
      
    </div>
    
      <div class="row" >
          <div class="col-md-4"></div>
          <div class="col-md-4">
              <h5><i class="fa fa-video"></i>Fotografía</h5>
              <input type="hidden" name="fotografia" id="id_fotografia">
                                        <button id="snap" type="button" class="btn btn-warning"><i class="fa fa-camera"></i> Tomar fotografía
                                        </button>
                                        
              <div style="display:none"> {{ form.info_person.imagen_base64 }}</div>

            </div>
          </div>
        </div>
      </div>
      <div class="row" >
      </br>
        <div class="col-md-6">
              <video id="video" width="640" height="480" autoplay></video>
          </div>
          <div class="col-md-12">

          <canvas id="canvas" width="640" height="480" style="margin-left: 40px"></canvas>



          </div>


          <div class="col-md-4"></div>

          <div class="col-md-4">
            <button type="submit" class="btn btn-success">Guardar</button>
          </div>
      </div>

      
    </br>

  </form>

    <script>

const downloadLink = document.getElementById('save');
let mediaRecorder;

//Toma de fotografías
let shouldStop = false;
let stopped = false;
let recordedChunks;


var video = document.getElementById('video');
var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');     
  

if (navigator.mediaDevices.getUserMedia) {
  navigator.mediaDevices.getUserMedia({ video: true })
    .then(function (stream) {
      video.srcObject = stream;
    })
    .catch(function (err0r) {
      //console.log("Something went wrong!");
    });
}


document.getElementById("snap").addEventListener("click", function() {
        context.drawImage(video, 0, 0, 640, 480);
        $("#id_imagen_base64").val(canvas.toDataURL("image/jpg"))
        return false;
    });


    </script>
{% endblock %}

templates/people/capacitacion/cursos.html
{% for curso in capacitacion %}
  <div>
    <img src="{{ curso.imagen_base64 }}" class="card-img-top" alt="...">
    <h5 class="card-title">{{ curso.nombre }}</h5>
    <a href="{% url 'capacitacion_curso' curso.pk %}" class="btn btn-default">Verificar Cumplimiento</a>
    <hr>
  </div>
{% endfor %}  